-- 회원보유인증번호 테이블
CREATE TABLE IF NOT EXISTS T_SG_A002 (
    SEQ_NO_A002 BIGINT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_A001 BIGINT NOT NULL,
    STD_CERT_NO VARCHAR(20) NOT NULL
    );

COMMENT ON TABLE T_SG_A002 IS '회원보유인증번호';
COMMENT ON COLUMN T_SG_A002.SEQ_NO_A002  IS '회원보유인증번호 순번';
COMMENT ON COLUMN T_SG_A002.SEQ_NO_A001  IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A002.STD_CERT_NO  IS '인증번호';

CREATE UNIQUE INDEX PK_T_SG_A002 ON T_SG_A002 (SEQ_NO_A002);

CREATE INDEX T_SG_A002_INX_01 ON T_SG_A002 (SEQ_NO_A001);

-- 친환경농산물인증정보 테이블
CREATE TABLE IF NOT EXISTS T_SG_A003 (
    SEQ_NO_A003 BIGINT AUTO_INCREMENT PRIMARY KEY,
    RCV_SEQ VARCHAR(30) NOT NULL,
    MOD_SEQ VARCHAR(30) NOT NULL,
    PRDR_GRP_NO VARCHAR(30) NOT NULL,
    REG_SEQ VARCHAR(30) NOT NULL,
    STD_CERT_NO VARCHAR(20),
    CERT_GB_CD VARCHAR(2),
    CERT_GB_NM VARCHAR(30),
    CERT_STRT_DT VARCHAR(20),
    CERT_END_DT VARCHAR(20),
    FRMR_CERT_STT VARCHAR(2),
    CERT_STATE_NM VARCHAR(30),
    PSN_GROUP_GB CHAR(1),
    PSN_GROUP_NM VARCHAR(20),
    PRDR_GRP_NM VARCHAR(200),
    REP_ITEM_CD VARCHAR(10),
    REP_ITEM_NM VARCHAR(100),
    FRMR_NO VARCHAR(30),
    FRMR_NM VARCHAR(200),
    ITEM_CD VARCHAR(10),
    ITEM_NM VARCHAR(100),
    REGIST_DATE DATE,
    STATUS CHAR(1)
    );

COMMENT ON TABLE T_SG_A003 IS '친환경농산물인증정보';
COMMENT ON COLUMN T_SG_A003.SEQ_NO_A003    IS '순번';
COMMENT ON COLUMN T_SG_A003.RCV_SEQ        IS '인증신청일련번호';
COMMENT ON COLUMN T_SG_A003.MOD_SEQ        IS '변경일련번호';
COMMENT ON COLUMN T_SG_A003.PRDR_GRP_NO    IS '생산자단체번호';
COMMENT ON COLUMN T_SG_A003.REG_SEQ        IS '등록일련번호';
COMMENT ON COLUMN T_SG_A003.STD_CERT_NO    IS '인증번호';
COMMENT ON COLUMN T_SG_A003.CERT_GB_CD     IS '인증구분코드 (1-유기농산물, 2-유기축산물, 3-무농약농산물, 4-저농약농산물, 5-무항생제축산물, 6-취급자, 7-수입자, 10-유기농산물(전환기) )';
COMMENT ON COLUMN T_SG_A003.CERT_GB_NM     IS '인증구분명 (유기농산물, 유기축산물, 무농약농산물, 저농약농산물, 무항생제축산물, 취급자, 수입자, 유기농산물(전환기))';
COMMENT ON COLUMN T_SG_A003.CERT_STRT_DT   IS '인증시작일자';
COMMENT ON COLUMN T_SG_A003.CERT_END_DT    IS '인증종료일자';
COMMENT ON COLUMN T_SG_A003.FRMR_CERT_STT  IS '인증상태코드 (6-인증, 8-인증취소, 12-기간종료, 13-인증포기)';
COMMENT ON COLUMN T_SG_A003.CERT_STATE_NM  IS '인증상태명 (인증, 인증취소, 기간종료, 인증포기)';
COMMENT ON COLUMN T_SG_A003.PSN_GROUP_GB   IS '개인단체구분 (1-개인, 2-단체)';
COMMENT ON COLUMN T_SG_A003.PSN_GROUP_NM   IS '개인단체구분명 (개인, 단체)';
COMMENT ON COLUMN T_SG_A003.PRDR_GRP_NM    IS '생산자단체명';
COMMENT ON COLUMN T_SG_A003.REP_ITEM_CD    IS '대표품목코드';
COMMENT ON COLUMN T_SG_A003.REP_ITEM_NM    IS '대표품목명';
COMMENT ON COLUMN T_SG_A003.FRMR_NO        IS '소속농가번호 (개인단체구분이 개인일 경우 NULL)';
COMMENT ON COLUMN T_SG_A003.FRMR_NM        IS '소속농가명 (개인단체구분이 개인일 경우 NULL)';
COMMENT ON COLUMN T_SG_A003.ITEM_CD        IS '품목코드';
COMMENT ON COLUMN T_SG_A003.ITEM_NM        IS '품목명';
COMMENT ON COLUMN T_SG_A003.REGIST_DATE    IS '등록일';
COMMENT ON COLUMN T_SG_A003.STATUS         IS '등록상태(I-입력, U-수정)';

-- 인덱스 생성
CREATE UNIQUE INDEX PK_T_SG_A003 ON T_SG_A003 (SEQ_NO_A003);

CREATE INDEX T_SG_A003_INX_01 ON T_SG_A003 (STD_CERT_NO);

CREATE INDEX T_SG_A003_INX_02 ON T_SG_A003 (RCV_SEQ, MOD_SEQ, PRDR_GRP_NO, REG_SEQ);

-- 상품바코드정보 테이블
CREATE TABLE IF NOT EXISTS T_SG_A004 (
    SEQ_NO_A004 BIGINT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_A003 BIGINT NOT NULL,
    SEQ_NO_A001 BIGINT NOT NULL,
    PRDR_BAR_CD VARCHAR(20) NOT NULL,
    PRDR_BAR_NM VARCHAR(200) NOT NULL,
    STATUS CHAR(1)
    );

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS T_SG_A004_INX_01 ON T_SG_A004 (SEQ_NO_A003);

CREATE INDEX IF NOT EXISTS T_SG_A004_INX_02 ON T_SG_A004 (SEQ_NO_A004, SEQ_NO_A003, SEQ_NO_A001);

-- 테이블에 대한 주석 추가
COMMENT ON TABLE T_SG_A004 IS '상품바코드정보';
COMMENT ON COLUMN T_SG_A004.SEQ_NO_A004 IS '상품바코드정보 순번';
COMMENT ON COLUMN T_SG_A004.SEQ_NO_A003 IS '친환경농산물인증정보 순번';
COMMENT ON COLUMN T_SG_A004.SEQ_NO_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A004.PRDR_BAR_CD IS '상품바코드';
COMMENT ON COLUMN T_SG_A004.PRDR_BAR_NM IS '상품명';
COMMENT ON COLUMN T_SG_A004.STATUS IS '등록상태(I-입력, U-수정)';



-- -------------------------------------------------
-- 회원정보 : T_SG_A001
-- -------------------------------------------------

CREATE TABLE T_SG_A001 (
   SEQ_NO_A001 BIGINT AUTO_INCREMENT PRIMARY KEY,  -- AUTO_INCREMENT 사용
   BNS_NO VARCHAR(10) NOT NULL,
   COMP_NM VARCHAR(100),
   COMP880_CD VARCHAR(20),
   COMP_TYPE CHAR(1) NOT NULL,
   REP_NM VARCHAR(100),
   REP_PHONE_NO VARCHAR(18),
   REP_FAX_NO VARCHAR(18),
   ZIPCODE VARCHAR(10),
   ADDR1 VARCHAR(100),
   ADDR2 VARCHAR(100),
   REGIST_DATE DATE DEFAULT CURRENT_DATE,
   APPROVAL_YN CHAR(1) NOT NULL,
   DEL_YN CHAR(1) NOT NULL
);

-- 테이블에 대한 설명을 H2는 지원하지 않으므로, 주석으로 추가합니다.
COMMENT ON TABLE T_SG_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A001.SEQ_NO_A001  IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A001.BNS_NO       IS '사업자등록번호';
COMMENT ON COLUMN T_SG_A001.COMP_NM      IS '회사명칭';
COMMENT ON COLUMN T_SG_A001.COMP880_CD   IS '(2013.03.18)업체코드가 다수 입력되어 사용안함. T_SG_A005로 대체';
COMMENT ON COLUMN T_SG_A001.COMP_TYPE    IS '업체구분 (1-생산자/취급자, 2-유통업체))';
COMMENT ON COLUMN T_SG_A001.REP_NM       IS '대표이름';
COMMENT ON COLUMN T_SG_A001.REP_PHONE_NO IS '대표전화';
COMMENT ON COLUMN T_SG_A001.REP_FAX_NO   IS '대표팩스';
COMMENT ON COLUMN T_SG_A001.ZIPCODE      IS '우편번호';
COMMENT ON COLUMN T_SG_A001.ADDR1        IS '주소';
COMMENT ON COLUMN T_SG_A001.ADDR2        IS '상세주소';
COMMENT ON COLUMN T_SG_A001.REGIST_DATE  IS '등록일';
COMMENT ON COLUMN T_SG_A001.APPROVAL_YN  IS '승인구분 (Y-승인, N-미승인))';
COMMENT ON COLUMN T_SG_A001.DEL_YN       IS '삭제구분 (Y-삭제, N-미삭제))';

-- 인덱스 생성 (H2는 기본적으로 여러 인덱스를 지원)
CREATE INDEX T_SG_A001_INX_01 ON T_SG_A001(BNS_NO);
CREATE INDEX T_SG_A001_INX_02 ON T_SG_A001(REGIST_DATE DESC, COMP_NM, REP_NM, COMP_TYPE, APPROVAL_YN, DEL_YN);


