-- -------------------------------------------------
-- 회원정보 : T_SG_A001
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_A001 (
    SEQ_NO_A001 INT AUTO_INCREMENT PRIMARY KEY,
    BNS_NO VARCHAR(10) NOT NULL,
    COMP_NM VARCHAR(100),
    COMP880_CD VARCHAR(20),
    COMP_TYPE CHAR(1) NOT NULL,
    REP_NM VARCHAR(100),
    REP_PHONE_NO VARCHAR(18),
    REP_FAX_NO VARCHAR(18),
    ZIPCODE VARCHAR(10),
    ADDR1 VARCHAR(100),
    ADDR2 VARCHAR(100),
    REGIST_DATE DATE DEFAULT CURRENT_DATE,
    APPROVAL_YN CHAR(1) NOT NULL,
    DEL_YN CHAR(1) NOT NULL
    );

CREATE INDEX T_SG_A001_INX_01 ON T_SG_A001 (BNS_NO);
CREATE INDEX T_SG_A001_INX_02 ON T_SG_A001 (REGIST_DATE DESC, COMP_NM, REP_NM, COMP_TYPE, APPROVAL_YN, DEL_YN);

COMMENT ON TABLE T_SG_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A001.SEQ_NO_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A001.BNS_NO IS '사업자등록번호';
COMMENT ON COLUMN T_SG_A001.COMP_NM IS '회사명칭';
COMMENT ON COLUMN T_SG_A001.COMP880_CD IS '사용안함 - 업체코드는 T_SG_A005 사용';
COMMENT ON COLUMN T_SG_A001.COMP_TYPE IS '업체구분 (1-생산자/취급자, 2-유통업체)';
COMMENT ON COLUMN T_SG_A001.REP_NM IS '대표이름';
COMMENT ON COLUMN T_SG_A001.REP_PHONE_NO IS '대표전화';
COMMENT ON COLUMN T_SG_A001.REP_FAX_NO IS '대표팩스';
COMMENT ON COLUMN T_SG_A001.ZIPCODE IS '우편번호';
COMMENT ON COLUMN T_SG_A001.ADDR1 IS '주소';
COMMENT ON COLUMN T_SG_A001.ADDR2 IS '상세주소';
COMMENT ON COLUMN T_SG_A001.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_A001.APPROVAL_YN IS '승인구분 (Y-승인, N-미승인)';
COMMENT ON COLUMN T_SG_A001.DEL_YN IS '삭제구분 (Y-삭제, N-미삭제)';

-- -------------------------------------------------
-- 회원보유인증번호 : T_SG_A002
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_A002 (
    SEQ_NO_A002 INT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_A001 INT NOT NULL,
    STD_CERT_NO VARCHAR(20) NOT NULL
    );

CREATE INDEX T_SG_A002_INX_01 ON T_SG_A002 (SEQ_NO_A001);

COMMENT ON TABLE T_SG_A002 IS '회원보유인증번호';
COMMENT ON COLUMN T_SG_A002.SEQ_NO_A002 IS '회원보유인증번호 순번';
COMMENT ON COLUMN T_SG_A002.SEQ_NO_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A002.STD_CERT_NO IS '인증번호';

-- -------------------------------------------------
-- 친환경농산물인증정보 : T_SG_A003
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_A003 (
    SEQ_NO_A003 INT AUTO_INCREMENT PRIMARY KEY,
    RCV_SEQ VARCHAR(30) NOT NULL,
    MOD_SEQ VARCHAR(30) NOT NULL,
    PRDR_GRP_NO VARCHAR(30) NOT NULL,
    REG_SEQ VARCHAR(30) NOT NULL,
    STD_CERT_NO VARCHAR(20),
    CERT_GB_CD VARCHAR(2),
    CERT_GB_NM VARCHAR(30),
    CERT_STRT_DT VARCHAR(20),
    CERT_END_DT VARCHAR(20),
    FRMR_CERT_STT VARCHAR(2),
    CERT_STATE_NM VARCHAR(30),
    PSN_GROUP_GB CHAR(1),
    PSN_GROUP_NM VARCHAR(20),
    PRDR_GRP_NM VARCHAR(200),
    REP_ITEM_CD VARCHAR(10),
    REP_ITEM_NM VARCHAR(100),
    FRMR_NO VARCHAR(30),
    FRMR_NM VARCHAR(200),
    ITEM_CD VARCHAR(10),
    ITEM_NM VARCHAR(100),
    REGIST_DATE DATE,
    STATUS CHAR(1)
    );

CREATE INDEX T_SG_A003_INX_01 ON T_SG_A003 (STD_CERT_NO);
CREATE INDEX T_SG_A003_INX_02 ON T_SG_A003 (RCV_SEQ, MOD_SEQ, PRDR_GRP_NO, REG_SEQ);

COMMENT ON TABLE T_SG_A003 IS '친환경농산물인증정보';
COMMENT ON COLUMN T_SG_A003.SEQ_NO_A003 IS '순번';
COMMENT ON COLUMN T_SG_A003.RCV_SEQ IS '인증신청일련번호';
COMMENT ON COLUMN T_SG_A003.MOD_SEQ IS '변경일련번호';
COMMENT ON COLUMN T_SG_A003.PRDR_GRP_NO IS '생산자단체번호';
COMMENT ON COLUMN T_SG_A003.REG_SEQ IS '등록일련번호';
COMMENT ON COLUMN T_SG_A003.STD_CERT_NO IS '인증번호';
COMMENT ON COLUMN T_SG_A003.CERT_GB_CD IS '인증구분코드';
COMMENT ON COLUMN T_SG_A003.CERT_GB_NM IS '인증구분명';
COMMENT ON COLUMN T_SG_A003.CERT_STRT_DT IS '인증시작일자';
COMMENT ON COLUMN T_SG_A003.CERT_END_DT IS '인증종료일자';
COMMENT ON COLUMN T_SG_A003.FRMR_CERT_STT IS '인증상태코드';
COMMENT ON COLUMN T_SG_A003.CERT_STATE_NM IS '인증상태명';
COMMENT ON COLUMN T_SG_A003.PSN_GROUP_GB IS '개인단체구분';
COMMENT ON COLUMN T_SG_A003.PSN_GROUP_NM IS '개인단체구분명';
COMMENT ON COLUMN T_SG_A003.PRDR_GRP_NM IS '생산자단체명';
COMMENT ON COLUMN T_SG_A003.REP_ITEM_CD IS '대표품목코드';
COMMENT ON COLUMN T_SG_A003.REP_ITEM_NM IS '대표품목명';
COMMENT ON COLUMN T_SG_A003.FRMR_NO IS '소속농가번호';
COMMENT ON COLUMN T_SG_A003.FRMR_NM IS '소속농가명';
COMMENT ON COLUMN T_SG_A003.ITEM_CD IS '품목코드';
COMMENT ON COLUMN T_SG_A003.ITEM_NM IS '품목명';
COMMENT ON COLUMN T_SG_A003.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_A003.STATUS IS '등록상태';

-- -------------------------------------------------
-- 상품바코드정보 : T_SG_A004
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_A004 (
    SEQ_NO_A004 INT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_A003 INT,
    SEQ_NO_A001 INT NOT NULL,
    PRDR_BAR_CD VARCHAR(20) NOT NULL,
    PRDR_BAR_NM VARCHAR(200) NOT NULL,
    STATUS CHAR(1)
    );

CREATE INDEX T_SG_A004_INX_01 ON T_SG_A004 (SEQ_NO_A003);
CREATE INDEX T_SG_A004_INX_02 ON T_SG_A004 (SEQ_NO_A004, SEQ_NO_A003, SEQ_NO_A001);

COMMENT ON TABLE T_SG_A004 IS '상품바코드정보';
COMMENT ON COLUMN T_SG_A004.SEQ_NO_A004 IS '상품바코드정보 순번';
COMMENT ON COLUMN T_SG_A004.SEQ_NO_A003 IS '친환경농산물인증정보 순번';
COMMENT ON COLUMN T_SG_A004.SEQ_NO_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_A004.PRDR_BAR_CD IS '상품바코드';
COMMENT ON COLUMN T_SG_A004.PRDR_BAR_NM IS '상품명';
COMMENT ON COLUMN T_SG_A004.STATUS IS '등록상태';



-- -------------------------------------------------
-- 대표상품정보 : T_SG_F001
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_F001 (
    SEQ_NO_F001 INT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_A001 INT NOT NULL,
    PRDR_BAR_CD VARCHAR(20) NOT NULL,
    PRDR_BAR_NM VARCHAR(200) NOT NULL,
    CERT_STATE VARCHAR(30),
    REGIST_DATE DATE DEFAULT CURRENT_DATE,
    DEL_YN CHAR(1) NOT NULL
    );

CREATE INDEX T_SG_F001_INX_01 ON T_SG_F001(PRDR_BAR_CD);
CREATE INDEX T_SG_F001_INX_02 ON T_SG_F001(REGIST_DATE DESC, PRDR_BAR_CD, PRDR_BAR_NM, CERT_STATE, DEL_YN);

COMMENT ON TABLE T_SG_F001 IS '대표상품정보';
COMMENT ON COLUMN T_SG_F001.SEQ_NO_F001 IS '대표상품정보 순번';
COMMENT ON COLUMN T_SG_F001.SEQ_NO_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_F001.PRDR_BAR_CD IS '대표상품바코드';
COMMENT ON COLUMN T_SG_F001.PRDR_BAR_NM IS '대표상품명';
COMMENT ON COLUMN T_SG_F001.CERT_STATE IS '인증상태정보 (전체취소, 정상)';
COMMENT ON COLUMN T_SG_F001.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_F001.DEL_YN IS '삭제구분 (Y-삭제, N-미삭제)';


-- -------------------------------------------------
-- 대표상품 생산자정보 : T_SG_F002
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_F002 (
     SEQ_NO_F002 INT AUTO_INCREMENT PRIMARY KEY,
     SEQ_NO_F001 INT NOT NULL,
     SEQ_NO_A003 INT,
     REGIST_DATE DATE DEFAULT CURRENT_DATE,
     DEL_YN CHAR(1) NOT NULL
    );

CREATE INDEX T_SG_F002_INX_01 ON T_SG_F002(SEQ_NO_F002, SEQ_NO_F001, SEQ_NO_A003);
CREATE INDEX T_SG_F002_INX_02 ON T_SG_F002(REGIST_DATE DESC, SEQ_NO_F002, SEQ_NO_F001, SEQ_NO_A003, DEL_YN);

COMMENT ON TABLE T_SG_F002 IS '대표상품 생산자정보';
COMMENT ON COLUMN T_SG_F002.SEQ_NO_F002 IS '대표상품 생산자정보 순번';
COMMENT ON COLUMN T_SG_F002.SEQ_NO_F001 IS '대표상품정보 순번';
COMMENT ON COLUMN T_SG_F002.SEQ_NO_A003 IS '친환경농산물인증정보 순번';
COMMENT ON COLUMN T_SG_F002.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_F002.DEL_YN IS '삭제구분 (Y-삭제, N-미삭제)';


-- -------------------------------------------------
-- 혼합상품정보 : T_SG_G001
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_G001 (
    SEQ_NO_G001 INT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_A001 INT NOT NULL,
    PRDR_BAR_CD VARCHAR(20) NOT NULL,
    PRDR_BAR_NM VARCHAR(200) NOT NULL,
    PRDR_COMP_NM VARCHAR(200),
    CERT_STATE VARCHAR(30),
    REGIST_DATE DATE DEFAULT CURRENT_DATE,
    DEL_YN CHAR(1) NOT NULL
    );

CREATE INDEX T_SG_G001_INX_01 ON T_SG_G001(PRDR_BAR_CD);
CREATE INDEX T_SG_G001_INX_02 ON T_SG_G001(REGIST_DATE DESC, PRDR_BAR_CD, PRDR_BAR_NM, PRDR_COMP_NM, DEL_YN);

COMMENT ON TABLE T_SG_G001 IS '혼합상품정보';
COMMENT ON COLUMN T_SG_G001.SEQ_NO_G001 IS '혼합상품정보 순번';
COMMENT ON COLUMN T_SG_G001.SEQ_NO_A001 IS '회원업체정보 순번';
COMMENT ON COLUMN T_SG_G001.PRDR_BAR_CD IS '혼합상품바코드';
COMMENT ON COLUMN T_SG_G001.PRDR_BAR_NM IS '혼합상품명';
COMMENT ON COLUMN T_SG_G001.PRDR_COMP_NM IS '취급자명';
COMMENT ON COLUMN T_SG_G001.CERT_STATE IS '인증상태정보';
COMMENT ON COLUMN T_SG_G001.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_G001.DEL_YN IS '삭제구분 (Y-삭제, N-미삭제)';


-- -------------------------------------------------
-- 구성상품정보 : T_SG_G002
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_G002 (
    SEQ_NO_G002 INT AUTO_INCREMENT PRIMARY KEY,
    SEQ_NO_G001 INT NOT NULL,
    PRDR_ITEM_NM VARCHAR(200),
    REGIST_DATE DATE DEFAULT CURRENT_DATE,
    DEL_YN CHAR(1) NOT NULL
    );



COMMENT ON TABLE T_SG_G002 IS '구성상품정보';
COMMENT ON COLUMN T_SG_G002.SEQ_NO_G002 IS '구성상품정보 순번';
COMMENT ON COLUMN T_SG_G002.SEQ_NO_G001 IS '혼합상품정보 순번';
COMMENT ON COLUMN T_SG_G002.PRDR_ITEM_NM IS '구성상품명';
COMMENT ON COLUMN T_SG_G002.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_G002.DEL_YN IS '삭제구분 (Y-삭제, N-미삭제)';


-- -------------------------------------------------
-- 구성상품 생산자정보 : T_SG_G003
-- -------------------------------------------------
CREATE TABLE IF NOT EXISTS T_SG_G003 (
     SEQ_NO_G003 INT AUTO_INCREMENT PRIMARY KEY,
     SEQ_NO_G002 INT NOT NULL,
     SEQ_NO_A003 INT,
     REGIST_DATE DATE DEFAULT CURRENT_DATE,
     DEL_YN CHAR(1) NOT NULL
    );



COMMENT ON TABLE T_SG_G003 IS '구성상품 생산자정보';
COMMENT ON COLUMN T_SG_G003.SEQ_NO_G003 IS '구성상품 생산자정보 순번';
COMMENT ON COLUMN T_SG_G003.SEQ_NO_G002 IS '구성상품정보 순번';
COMMENT ON COLUMN T_SG_G003.SEQ_NO_A003 IS '친환경농산물인증정보 순번';
COMMENT ON COLUMN T_SG_G003.REGIST_DATE IS '등록일';
COMMENT ON COLUMN T_SG_G003.DEL_YN IS '삭제구분 (Y-삭제, N-미삭제)';